# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 5, size: 0.112},
    {id: 6, size: 0.112},
    {id: 7, size: 0.112},
    {id: 8, size: 0.112},
    {id: 10, size: 0.112},
    {id: 20, size: 0.112}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          {id: 0, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 1, size: 0.05, x: -0.0769, y: 0.0751, z: 0.0093, qw: 0.9997, qx: 0.0147, qy: 0.0205, qz: 0.0026},
          {id: 2, size: 0.05, x: 0.0766, y: 0.0772, z: 0.0004, qw: 0.9998, qx: -0.0147, qy: -0.0091, qz: -0.0030},
          {id: 3, size: 0.05, x: -0.0766, y: -0.0760, z: -0.0041, qw: 0.9996, qx: -0.0011, qy: 0.0295, qz: 0.0015},
          {id: 4, size: 0.05, x: 0.0761, y: -0.0777, z: 0.0032, qw: 0.9921, qx: 0.0954, qy: -0.0814, qz: -0.0016}
        ]
    }
  ]
